<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HUBLAPINDCE-018" failures="1" tests="6" name="DataProvider test" time="0.249" errors="0" timestamp="2022-12-24T22:29:09 IST">
  <testcase classname="practice.DataProvider1" name="LoginTest1" time="0.032">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at practice.DataProvider1.LoginTest1(DataProvider1.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest1 -->
  <testcase classname="practice.DataProvider1" name="LoginTest2" time="0.01"/>
  <testcase classname="practice.DataProvider1" name="LoginTest3" time="0.004"/>
  <testcase classname="practice.DataProvider1" name="LoginTest3" time="0.004"/>
  <testcase classname="practice.DataProvider1" name="LoginTest3" time="0.002"/>
  <testcase classname="practice.DataProvider1" name="LoginTest4" time="0.002"/>
</testsuite> <!-- DataProvider test -->
